### ISSUE TITLE
inline javascript not called

### ISSUE THREAD

**Issue by waf7225** [falsandtru/pjax-api#29]
Hi,
I just discovered pjax not execute the inline script when i'm using safari, but other browser works fine.

Safari version 10.1.2 (12603.3.8)

**Comment by falsandtru** [comment]
The reason is Safari doesn't evaluate a script by dom injection.

https://github.com/falsandtru/pjax-api/blob/bad289372c8fd9aaa397b256975151ddb44a573b/src/layer/domain/router/module/update/script.ts#L124

However if I use `eval` function instead, `document.currentScript` support will be removed. Any ideas?

**Comment by falsandtru** [comment]
Fixed.
